---
- hosts: TomcatServer
  vars:
  - warName: SimpleTomcatWebApp.war
  - warRemotePath: /usr/local/apache-tomcat-9.0.2/webapps

  tasks:
  - name: Download WAR to server
    command: wget https://s3.amazonaws.com/mynewtesting/jararchive/target/SimpleTomcatWebApp.war -O {{ warRemotePath }}/{{ warName }}
  
  handlers:
    - name: Restart tomcat9
      service: name=tomcat9 state=restarted
